export const REMOTE_AUTH_REQUEST_URL = __ATTACHED_REMOTE_AUTH_REQUEST_URL__.trim()
export const REMOTE_AUTH_SIGN_IN_URL = __ATTACHED_REMOTE_AUTH_SIGN_IN_URL__.trim()
export const REMOTE_AUTH_TIMEOUT_MS = Math.max(2_000, __ATTACHED_REMOTE_AUTH_TIMEOUT_MS__)

export const REMOTE_AUTH_REQUEST_ENABLED = REMOTE_AUTH_REQUEST_URL.length > 0
export const REMOTE_AUTH_APPROVAL_SYNC_ENABLED = REMOTE_AUTH_SIGN_IN_URL.length > 0
