export const CHANNELS = {
  getAuthSnapshot: 'attached:auth:get',
  signIn: 'attached:auth:sign-in',
  submitAccessRequest: 'attached:auth:submit-access-request',
  signOut: 'attached:auth:sign-out',
  resetLocalData: 'attached:auth:reset-local-data',
  updateProfile: 'attached:auth:update-profile',
  updateEmail: 'attached:auth:update-email',
  changePassword: 'attached:auth:change-password',
  getAdminSnapshot: 'attached:admin:get',
  reviewAccessRequest: 'attached:admin:review-access-request',
  getDashboard: 'attached:dashboard:get',
  listSessions: 'attached:sessions:list',
  createSession: 'attached:sessions:create',
  getSession: 'attached:sessions:get',
  abortSession: 'attached:sessions:abort',
  deleteSessionRecordings: 'attached:sessions:delete-recordings',
  seedDebugSession: 'attached:sessions:seed-debug',
  updateIdentity: 'attached:sessions:update-identity',
  submitConsent: 'attached:sessions:submit-consent',
  revokeConsent: 'attached:sessions:revoke-consent',
  updateStep: 'attached:sessions:update-step',
  saveArtifact: 'attached:sessions:save-artifact',
  saveQuestionnaire: 'attached:sessions:save-questionnaire',
  startInference: 'attached:inference:start',
  getInferenceStatus: 'attached:inference:get-status',
  submitResultFeedback: 'attached:inference:submit-feedback'
} as const
